version: "3.1"

services:

  r-worker:
    build:
      context: ./
      dockerfile: Dockerfile
      target: r-worker
    image: syoh/r-worker:b6fdd5dae6cb
    command: >
      bash -c "
      /opt/conda/bin/future-vars.sh
      --run-mode worker
      --scheduler r-notebook
      --port 11562
      "
    deploy:
      replicas: 2

  rstudio:
    build:
      context: ./
      dockerfile: Dockerfile
      target: rstudio
    image: syoh/r-notebook:b6fdd5dae6cb
    hostname: r-notebook
    ports:
      - "8888:8888"
      - "11562:11562"
    command: >
      bash -c "
      /opt/conda/bin/future-vars.sh
      --run-mode scheduler
      --port 11562
      --n-workers 2;
      start-notebook.sh
      --ServerApp.custom_display_url='http://127.0.0.1:8888/rstudio'
      "