name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get build cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            buildx-
      -
        name: Create worker image tag
        id: worker_meta
        uses: docker/metadata-action@v3
        with:
          images: dddlab/r-future
          tags: type=sha,prefix=worker-
      -
        name: Build and push worker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.worker_meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          target: r-worker
      -
        name: Create Rstudio image tag
        id: rstudio_meta
        uses: docker/metadata-action@v3
        with:
          images: dddlab/r-future
          tags: type=sha,prefix=rstudio-
      -
        name: Build and push Rstudio image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.rstudio_meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          target: rstudio